# Generated by Django 4.1.4 on 2022-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('Stok', models.IntegerField()),
            ],
        ),
    ]
