# Generated by Django 4.1.4 on 2022-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_stok_menu_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
