# Generated by Django 4.1.4 on 2022-12-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_promosi'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
